#%RAML 1.0
title: api-error-handler-global-raml
version: v1
mediaType: application/json

uses:
  global-resources: /exchange_modules/f8f9abd2-10a0-400f-bb5b-60cbd5b8cb29/global-resources-fragments/1.0.0/global-resources-fragments.raml


/error-handler:
  description: Manage information for a specific error.
  is: [ global-resources.ErrorResponses, global-resources.PostErrorHandler ]
  post:
    description: Return details for an existing errors.